(* tools/gen_stdlib_sources.ml
   Reads stdlib/*.mml files passed as arguments and generates
   lib/stdlib_sources.ml with OCaml string constants.

   Usage: ocaml gen_stdlib_sources.ml file1.mml file2.mml ... *)

let () =
  let args = Array.to_list (Array.sub Sys.argv 1 (Array.length Sys.argv - 1)) in
  let mml_files = List.filter (fun f -> Filename.check_suffix f ".mml") args in
  Printf.printf "(* Generated by tools/gen_stdlib_sources.ml — do not edit *)\n\n";
  List.iter (fun path ->
    let basename = Filename.basename path in
    let name = Filename.chop_extension basename in
    let ic = open_in path in
    let n = in_channel_length ic in
    let content = really_input_string ic n in
    close_in ic;
    Printf.printf "let %s = {stdlib|%s|stdlib}\n\n" name content
  ) mml_files
